import FWCore.ParameterSet.Config as cms
import copy

process = cms.Process('HiMassTau')

process.load('Configuration.StandardSequences.Services_cff')
process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')
from Configuration.AlCa.autoCond import autoCond
process.GlobalTag.globaltag = cms.string( autoCond[ 'startup' ] )
#process.GlobalTag.globaltag = 'START42_V13::All'
process.load('JetMETCorrections.Configuration.JetCorrectionServices_cff')
process.load('CommonTools/RecoAlgos/HBHENoiseFilter_cfi')
process.load('FWCore.MessageService.MessageLogger_cfi')
process.MessageLogger.cerr.FwkReport.reportEvery = 100

process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32( -1 )
)
process.source = cms.Source("PoolSource",
    skipEvents = cms.untracked.uint32(0),
    fileNames = cms.untracked.vstring(
)
)

process.TFileService = cms.Service("TFileService", 
    fileName = cms.string("analysis.root")
)

process.analyzeHiMassTau = cms.EDAnalyzer('HiMassTauAnalysis')

process.analyzeHiMassTau.DoMSUGRApoint = cms.bool(False)
process.analyzeHiMassTau.Prefix    = cms.string('susyScan')
process.analyzeHiMassTau.Suffix    = cms.string('')
process.analyzeHiMassTau.ScanFormat = cms.string(r"# model msugra_(\\d*)_(\\d*)_(m?\\d*)_(m?\\d*)_(m?\\d)\\s")
process.analyzeHiMassTau.ScanParameters = cms.vstring('M0', 'M12', 'tanbeta', 'A0', 'Mu')

process.analyzeHiMassTau.DoSMpoint = cms.bool(False)
process.analyzeHiMassTau.mLSP = cms.double(425.)
process.analyzeHiMassTau.mGL = cms.double(1150.)

    #-----Generator level Inputs
process.analyzeHiMassTau.GenParticleSource = cms.untracked.InputTag('genParticles')				# gen particle collection
process.analyzeHiMassTau.GenTauPtMinCut = cms.double(0.)
process.analyzeHiMassTau.GenTauEtaMaxCut = cms.double(999.)
process.analyzeHiMassTau.SelectSusyScanPoint = cms.bool(False)
process.analyzeHiMassTau.M0 = cms.double(400.)
process.analyzeHiMassTau.M12 = cms.double(360.)

    #-----Reco Tau Inputs
process.analyzeHiMassTau.RecoTauSource = cms.InputTag('selectedPatTaus')
process.analyzeHiMassTau.RecoTau1EtaCut = cms.double(2.1)
process.analyzeHiMassTau.RecoTau1PtMinCut = cms.double(30.)					
process.analyzeHiMassTau.RecoTau1PtMaxCut = cms.double(9999.)					
process.analyzeHiMassTau.DoRecoTau1DiscrByLeadTrack = cms.bool(False) 				
process.analyzeHiMassTau.UseRecoTau1DiscrByLeadTrackFlag = cms.bool(True) 			
process.analyzeHiMassTau.RecoTau1DiscrByLeadTrack = cms.untracked.string('leadingPionPtCut')	
process.analyzeHiMassTau.DoRecoTau1DiscrByLeadTrackNhits = cms.bool(False)			
process.analyzeHiMassTau.RecoTau1LeadTrackMinHits = cms.int32(12)				
process.analyzeHiMassTau.DoRecoTau1DiscrByH3x3OverP = cms.bool(False)				
process.analyzeHiMassTau.RecoTau1H3x3OverP = cms.double(0.03)					
process.analyzeHiMassTau.DoRecoTau1DiscrByIsolation = cms.bool(False) 				
process.analyzeHiMassTau.UseRecoTau1DiscrByIsolationFlag = cms.bool(False) 			
process.analyzeHiMassTau.RecoTau1DiscrByIsolation = cms.untracked.string('byTightIsolationMVA')	
process.analyzeHiMassTau.UseRecoTau1IsoSumPtInsteadOfNiso = cms.bool(False)			
process.analyzeHiMassTau.UseRecoTau1EllipseForEcalIso = cms.bool(False)				
process.analyzeHiMassTau.RecoTau1EcalIsoRphiForEllipse = cms.double(0.15)			
process.analyzeHiMassTau.RecoTau1EcalIsoRetaForEllipse = cms.double(0.07)			
process.analyzeHiMassTau.RecoTau1TrackNisoMax = cms.int32(0)					
process.analyzeHiMassTau.RecoTau1EcalNisoMax = cms.int32(0)					
process.analyzeHiMassTau.RecoTau1TrackIsoSumPtMaxCutValue = cms.double(1.0)			
process.analyzeHiMassTau.RecoTau1TrackIsoSumPtMinCutValue = cms.double(0.0)			
process.analyzeHiMassTau.RecoTau1EcalIsoSumPtMaxCutValue = cms.double(1.0)			
process.analyzeHiMassTau.RecoTau1EcalIsoSumPtMinCutValue = cms.double(0.0)			
process.analyzeHiMassTau.RecoTau1DiscrByProngType = cms.string('1or3hps')  		 	
process.analyzeHiMassTau.RecoTau1LeadTrackThreshold = cms.double(5.0) 				
process.analyzeHiMassTau.RecoTau1SigGamThreshold = cms.double(1.0)				
process.analyzeHiMassTau.RecoTau1IsoDeltaRCone = cms.double(0.5)	 				
process.analyzeHiMassTau.RecoTau1TrackIsoTrkThreshold = cms.double(0.8) 				
process.analyzeHiMassTau.RecoTau1GammaIsoGamThreshold = cms.double(0.8) 				
process.analyzeHiMassTau.DoRecoTau1DiscrAgainstElectron = cms.bool(True)				
process.analyzeHiMassTau.RecoTau1DiscrAgainstElectron = cms.untracked.string('againstElectronTightMVA2')
process.analyzeHiMassTau.DoRecoTau1DiscrByCrackCut = cms.bool(False)				
process.analyzeHiMassTau.DoRecoTau1DiscrAgainstMuon = cms.bool(True) 			
process.analyzeHiMassTau.RecoTau1DiscrAgainstMuon = cms.untracked.string('againstMuonTight')
process.analyzeHiMassTau.SelectTau1sThatAreMuons = cms.bool(False)
process.analyzeHiMassTau.SelectTau1sThatAreElectrons = cms.bool(False)

process.analyzeHiMassTau.RecoTau2EtaCut = cms.double(999.1)
process.analyzeHiMassTau.RecoTau2PtMinCut = cms.double(0.)
process.analyzeHiMassTau.RecoTau2PtMaxCut = cms.double(9999.)
process.analyzeHiMassTau.DoRecoTau2DiscrByLeadTrack = cms.bool(False)
process.analyzeHiMassTau.UseRecoTau2DiscrByLeadTrackFlag = cms.bool(True)
process.analyzeHiMassTau.RecoTau2DiscrByLeadTrack = cms.untracked.string('leadingPionPtCut')
process.analyzeHiMassTau.DoRecoTau2DiscrByLeadTrackNhits = cms.bool(False)
process.analyzeHiMassTau.RecoTau2LeadTrackMinHits = cms.int32(12)
process.analyzeHiMassTau.DoRecoTau2DiscrByH3x3OverP = cms.bool(False)
process.analyzeHiMassTau.RecoTau2H3x3OverP = cms.double(0.03)
process.analyzeHiMassTau.DoRecoTau2DiscrByIsolation = cms.bool(False)
process.analyzeHiMassTau.UseRecoTau2DiscrByIsolationFlag = cms.bool(False)
process.analyzeHiMassTau.RecoTau2DiscrByIsolation = cms.untracked.string('byTightIsolationMVA')
process.analyzeHiMassTau.UseRecoTau2IsoSumPtInsteadOfNiso = cms.bool(False)
process.analyzeHiMassTau.UseRecoTau2EllipseForEcalIso = cms.bool(False)
process.analyzeHiMassTau.RecoTau2EcalIsoRphiForEllipse = cms.double(0.15)
process.analyzeHiMassTau.RecoTau2EcalIsoRetaForEllipse = cms.double(0.07)
process.analyzeHiMassTau.RecoTau2TrackNisoMax = cms.int32(0)
process.analyzeHiMassTau.RecoTau2EcalNisoMax = cms.int32(0)
process.analyzeHiMassTau.RecoTau2TrackIsoSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.RecoTau2TrackIsoSumPtMinCutValue = cms.double(0.0)
process.analyzeHiMassTau.RecoTau2EcalIsoSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.RecoTau2EcalIsoSumPtMinCutValue = cms.double(0.0)
process.analyzeHiMassTau.RecoTau2DiscrByProngType = cms.string('NONE')
process.analyzeHiMassTau.RecoTau2LeadTrackThreshold = cms.double(5.0)
process.analyzeHiMassTau.RecoTau2SigGamThreshold = cms.double(1.0)
process.analyzeHiMassTau.RecoTau2IsoDeltaRCone = cms.double(0.5)
process.analyzeHiMassTau.RecoTau2TrackIsoTrkThreshold = cms.double(0.8)
process.analyzeHiMassTau.RecoTau2GammaIsoGamThreshold = cms.double(0.8)
process.analyzeHiMassTau.DoRecoTau2DiscrAgainstElectron = cms.bool(False)
process.analyzeHiMassTau.RecoTau2DiscrAgainstElectron = cms.untracked.string('againstElectronTightMVA2')
process.analyzeHiMassTau.DoRecoTau2DiscrByCrackCut = cms.bool(False)
process.analyzeHiMassTau.DoRecoTau2DiscrAgainstMuon = cms.bool(False)
process.analyzeHiMassTau.RecoTau2DiscrAgainstMuon = cms.untracked.string('againstMuonTight')
process.analyzeHiMassTau.SelectTau2sThatAreMuons = cms.bool(False)
process.analyzeHiMassTau.SelectTau2sThatAreElectrons = cms.bool(False)

    #-----Reco Muon Inputs
process.analyzeHiMassTau.RecoMuonSource = cms.InputTag('selectedPatMuons')				       
#process.analyzeHiMassTau.IsoValMuonPF = cms.VInputTag(cms.InputTag('muPFIsoValueCharged04PFIso'),
#                                        cms.InputTag('muPFIsoValueGamma04PFIso'),
#                                        cms.InputTag('muPFIsoValueNeutral04PFIso'))
process.analyzeHiMassTau.RecoMuon1EtaCut = cms.double(2.1)					
process.analyzeHiMassTau.RecoMuon1PtMinCut = cms.double(25.)					
process.analyzeHiMassTau.RecoMuon1PtMaxCut = cms.double(9999.)					
process.analyzeHiMassTau.DoRecoMuon1DiscrByGlobal = cms.bool(True)				
process.analyzeHiMassTau.DoRecoMuon1DiscrByIsolation = cms.bool(True)				
process.analyzeHiMassTau.RecoMuon1TrackIsoSumPtMaxCutValue = cms.double(0.1)			
process.analyzeHiMassTau.RecoMuon1TrackIsoSumPtMinCutValue = cms.double(0.0)			
process.analyzeHiMassTau.RecoMuon1EcalIsoSumPtMaxCutValue = cms.double(1.0)			
process.analyzeHiMassTau.RecoMuon1EcalIsoSumPtMinCutValue = cms.double(0.0)			
process.analyzeHiMassTau.RecoMuon1IsoDeltaRCone = cms.double(0.4)				
process.analyzeHiMassTau.RecoMuon1TrackIsoTrkThreshold = cms.double(1.0)				
process.analyzeHiMassTau.RecoMuon1EcalIsoRecHitThreshold = cms.double(1.0)			
process.analyzeHiMassTau.DoRecoMuon1DiscrByIp = cms.bool(True)					
process.analyzeHiMassTau.RecoMuon1IpCut = cms.double(0.2)					
process.analyzeHiMassTau.DoRecoMuon1DiscrByPionVeto = cms.bool(False)                           
process.analyzeHiMassTau.RecoMuon1CaloCompCoefficient = cms.double(0.8)                         
process.analyzeHiMassTau.RecoMuon1SegmCompCoefficient = cms.double(1.2)                         
process.analyzeHiMassTau.RecoMuon1AntiPionCut = cms.double(1.0)                                 
process.analyzeHiMassTau.DoRecoMuon1DiscrByNormalizedChi2 = cms.bool(True)
process.analyzeHiMassTau.RecoMuon1NormalizedChi2MaxCut = cms.int32(10)
process.analyzeHiMassTau.DoRecoMuon1DiscrByChamberHits = cms.bool(True)
process.analyzeHiMassTau.RecoMuon1ChamberHitsMinCut = cms.int32(0)
process.analyzeHiMassTau.DoRecoMuon1DiscrByMatchedStations = cms.bool(True)
process.analyzeHiMassTau.RecoMuon1MatchedStationsMinCut = cms.int32(1)
process.analyzeHiMassTau.DoRecoMuon1DiscrByPixelHits = cms.bool(True)
process.analyzeHiMassTau.RecoMuon1PixelHitsMinCut = cms.int32(0)
process.analyzeHiMassTau.DoRecoMuon1DiscrByTrackerLayerWithHits = cms.bool(True)
process.analyzeHiMassTau.RecoMuon1TrackerLayerWithHitsMinCut = cms.int32(5)

process.analyzeHiMassTau.RecoMuon2EtaCut = cms.double(999.1)
process.analyzeHiMassTau.RecoMuon2PtMinCut = cms.double(0.)
process.analyzeHiMassTau.RecoMuon2PtMaxCut = cms.double(9999.)
process.analyzeHiMassTau.DoRecoMuon2DiscrByGlobal = cms.bool(True)
process.analyzeHiMassTau.DoRecoMuon2DiscrByIsolation = cms.bool(False)
process.analyzeHiMassTau.RecoMuon2TrackIsoSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.RecoMuon2TrackIsoSumPtMinCutValue = cms.double(0.0)
process.analyzeHiMassTau.RecoMuon2EcalIsoSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.RecoMuon2EcalIsoSumPtMinCutValue = cms.double(0.0)
process.analyzeHiMassTau.RecoMuon2IsoDeltaRCone = cms.double(0.4)
process.analyzeHiMassTau.RecoMuon2TrackIsoTrkThreshold = cms.double(1.0)
process.analyzeHiMassTau.RecoMuon2EcalIsoRecHitThreshold = cms.double(1.0)
process.analyzeHiMassTau.DoRecoMuon2DiscrByIp = cms.bool(False)
process.analyzeHiMassTau.RecoMuon2IpCut = cms.double(0.2)
process.analyzeHiMassTau.DoRecoMuon2DiscrByPionVeto = cms.bool(False)
process.analyzeHiMassTau.RecoMuon2CaloCompCoefficient = cms.double(0.8)
process.analyzeHiMassTau.RecoMuon2SegmCompCoefficient = cms.double(1.2)
process.analyzeHiMassTau.RecoMuon2AntiPionCut = cms.double(1.0)
process.analyzeHiMassTau.DoRecoMuon2DiscrByNormalizedChi2 = cms.bool(False)
process.analyzeHiMassTau.RecoMuon2NormalizedChi2MaxCut = cms.int32(10)
process.analyzeHiMassTau.DoRecoMuon2DiscrByChamberHits = cms.bool(False)
process.analyzeHiMassTau.RecoMuon2ChamberHitsMinCut = cms.int32(0)
process.analyzeHiMassTau.DoRecoMuon2DiscrByMatchedStations = cms.bool(False)
process.analyzeHiMassTau.RecoMuon2MatchedStationsMinCut = cms.int32(1)
process.analyzeHiMassTau.DoRecoMuon2DiscrByPixelHits = cms.bool(False)
process.analyzeHiMassTau.RecoMuon2PixelHitsMinCut = cms.int32(0)
process.analyzeHiMassTau.DoRecoMuon2DiscrByTrackerLayerWithHits = cms.bool(False)
process.analyzeHiMassTau.RecoMuon2TrackerLayerWithHitsMinCut = cms.int32(5)

    #-----Reco Electron Inputs
process.analyzeHiMassTau.RecoElectronSource = cms.InputTag('heepPatElectrons')			        
process.analyzeHiMassTau.UseHeepInfo = cms.bool(True)							
process.analyzeHiMassTau.RecoElectron1EtaCut = cms.double(999.1)						
process.analyzeHiMassTau.RecoElectron1PtMinCut = cms.double(0.)						
process.analyzeHiMassTau.RecoElectron1PtMaxCut = cms.double(9999.)					
process.analyzeHiMassTau.DoRecoElectron1DiscrByTrackIsolation = cms.bool(False) 				
process.analyzeHiMassTau.RecoElectron1TrackIsoSumPtMaxCutValue = cms.double(1.0) 			
process.analyzeHiMassTau.RecoElectron1TrackIsoSumPtMinCutValue = cms.double(0.0) 			
process.analyzeHiMassTau.RecoElectron1TrackIsoDeltaRCone = cms.double(0.4) 				
process.analyzeHiMassTau.RecoElectron1TrackIsoTrkThreshold = cms.double(1.0) 				
process.analyzeHiMassTau.DoRecoElectron1DiscrByEcalIsolation = cms.bool(False) 				
process.analyzeHiMassTau.RecoElectron1EcalIsoSumPtMaxCutValue = cms.double(1.0) 				
process.analyzeHiMassTau.RecoElectron1EcalIsoSumPtMinCutValue = cms.double(0.0) 				
process.analyzeHiMassTau.RecoElectron1EcalIsoDeltaRCone = cms.double(0.4) 				
process.analyzeHiMassTau.RecoElectron1EcalIsoRecHitThreshold = cms.double(1.0)				
process.analyzeHiMassTau.DoRecoElectron1DiscrByIp = cms.bool(False) 					
#    process.analyzeHiMassTau.RecoElectron1IpCut = cms.double(999.) 					
process.analyzeHiMassTau.DoRecoElectron1DiscrByEoverP = cms.bool(False) 					
#    process.analyzeHiMassTau.RecoElectron1EoverPMax = cms.double(1.3) 					
#    process.analyzeHiMassTau.RecoElectron1EoverPMin = cms.double(0.7) 					
process.analyzeHiMassTau.DoRecoElectron1DiscrByHoverEm = cms.bool(False) 				
#    process.analyzeHiMassTau.RecoElectron1HoverEmCut = cms.double(0.05)	 				
process.analyzeHiMassTau.DoRecoElectron1DiscrBySigmaIEtaIEta = cms.bool(False)				
#    process.analyzeHiMassTau.RecoElectron1SigmaIEtaIEta = cms.double(0.03)				
process.analyzeHiMassTau.DoRecoElectron1DiscrByDEtaIn = cms.bool(False)					 
#    process.analyzeHiMassTau.RecoElectron1EEDEtaIn = cms.double(0.007)
#    process.analyzeHiMassTau.RecoElectron1EBDEtaIn = cms.double(0.005)
process.analyzeHiMassTau.DoRecoElectron1DiscrByDPhiIn = cms.bool(False)
#    process.analyzeHiMassTau.RecoElectron1EEDPhiIn = cms.double(0.09)
#    process.analyzeHiMassTau.RecoElectron1EBDPhiIn = cms.double(0.09)
process.analyzeHiMassTau.DoRecoElectron1DiscrBySCE2by5Over5by5 = cms.bool(False)			
#    process.analyzeHiMassTau.RecoElectron1EBscE1by5Over5by5 = cms.double(0.83)					
#    process.analyzeHiMassTau.RecoElectron1EBscE2by5Over5by5 = cms.double(0.94)					
process.analyzeHiMassTau.DoRecoElectron1DiscrByMissingHits = cms.bool(False)
#    process.analyzeHiMassTau.RecoElectron1MissingHits = cms.int32(1)
#    process.analyzeHiMassTau.DoRecoElectron1DiscrByEcalDrivenSeed = cms.bool(False)			
#    process.analyzeHiMassTau.DoRecoElectron1DiscrByTrackerDrivenSeed = cms.bool(False)			

process.analyzeHiMassTau.RecoElectron2EtaCut = cms.double(999.1)
process.analyzeHiMassTau.RecoElectron2PtMinCut = cms.double(0.)
process.analyzeHiMassTau.RecoElectron2PtMaxCut = cms.double(9999.)
process.analyzeHiMassTau.DoRecoElectron2DiscrByTrackIsolation = cms.bool(False)
process.analyzeHiMassTau.RecoElectron2TrackIsoSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.RecoElectron2TrackIsoSumPtMinCutValue = cms.double(0.0)
process.analyzeHiMassTau.RecoElectron2TrackIsoDeltaRCone = cms.double(0.4)
process.analyzeHiMassTau.RecoElectron2TrackIsoTrkThreshold = cms.double(1.0)
process.analyzeHiMassTau.DoRecoElectron2DiscrByEcalIsolation = cms.bool(False)
process.analyzeHiMassTau.RecoElectron2EcalIsoSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.RecoElectron2EcalIsoSumPtMinCutValue = cms.double(0.0)
process.analyzeHiMassTau.RecoElectron2EcalIsoDeltaRCone = cms.double(0.4)
process.analyzeHiMassTau.RecoElectron2EcalIsoRecHitThreshold = cms.double(1.0)
process.analyzeHiMassTau.DoRecoElectron2DiscrByIp = cms.bool(False)
#    process.analyzeHiMassTau.RecoElectron2IpCut = cms.double(999.)
process.analyzeHiMassTau.DoRecoElectron2DiscrByEoverP = cms.bool(False)
#    process.analyzeHiMassTau.RecoElectron2EoverPMax = cms.double(1.3)
#    process.analyzeHiMassTau.RecoElectron2EoverPMin = cms.double(0.7)
process.analyzeHiMassTau.DoRecoElectron2DiscrByHoverEm = cms.bool(False)
#    process.analyzeHiMassTau.RecoElectron2HoverEmCut = cms.double(0.05)
process.analyzeHiMassTau.DoRecoElectron2DiscrBySigmaIEtaIEta = cms.bool(False)
#    process.analyzeHiMassTau.RecoElectron2SigmaIEtaIEta = cms.double(0.03)
process.analyzeHiMassTau.DoRecoElectron2DiscrByDEtaIn = cms.bool(False)
#    process.analyzeHiMassTau.RecoElectron2EEDEtaIn = cms.double(0.007)
#    process.analyzeHiMassTau.RecoElectron2EBDEtaIn = cms.double(0.005)
process.analyzeHiMassTau.DoRecoElectron2DiscrByDPhiIn = cms.bool(False)
#    process.analyzeHiMassTau.RecoElectron2EEDPhiIn = cms.double(0.09)
#    process.analyzeHiMassTau.RecoElectron2EBDPhiIn = cms.double(0.09)
process.analyzeHiMassTau.DoRecoElectron2DiscrBySCE2by5Over5by5 = cms.bool(False)
#    process.analyzeHiMassTau.RecoElectron2EBscE1by5Over5by5 = cms.double(0.83)
#    process.analyzeHiMassTau.RecoElectron2EBscE2by5Over5by5 = cms.double(0.94)
process.analyzeHiMassTau.DoRecoElectron2DiscrByMissingHits = cms.bool(False)
#    process.analyzeHiMassTau.RecoElectron2MissingHits = cms.int32(1)
#    process.analyzeHiMassTau.DoRecoElectron2DiscrByEcalDrivenSeed = cms.bool(False)
#    process.analyzeHiMassTau.DoRecoElectron2DiscrByTrackerDrivenSeed = cms.bool(False)

    #-----Reco Jet Inputs
process.analyzeHiMassTau.RecoJetSource                       = cms.InputTag('patJets')              
process.analyzeHiMassTau.RecoJetEtaMinCut                    = cms.double(2.1)                        
process.analyzeHiMassTau.RecoJetEtaMaxCut                    = cms.double(5.0)                      
process.analyzeHiMassTau.RecoJetPtCut                        = cms.double(15.0)                       
process.analyzeHiMassTau.UseCorrectedJet                     = cms.bool(True)                         
process.analyzeHiMassTau.ApplyJetLooseID                     = cms.bool(True)
process.analyzeHiMassTau.RemoveJetOverlapWithMuon1s           = cms.bool(True)                        
process.analyzeHiMassTau.JetMuon1MatchingDeltaR               = cms.double(0.4)                        
process.analyzeHiMassTau.RemoveJetOverlapWithElectron1s       = cms.bool(False)                        
process.analyzeHiMassTau.JetElectron1MatchingDeltaR           = cms.double(0.5)                        
process.analyzeHiMassTau.RemoveJetOverlapWithTau1s            = cms.bool(False)                        
process.analyzeHiMassTau.JetTau1MatchingDeltaR                = cms.double(0.25)                       
process.analyzeHiMassTau.RemoveJetOverlapWithMuon2s           = cms.bool(False)
process.analyzeHiMassTau.JetMuon2MatchingDeltaR               = cms.double(0.5)
process.analyzeHiMassTau.RemoveJetOverlapWithElectron2s       = cms.bool(False)
process.analyzeHiMassTau.JetElectron2MatchingDeltaR           = cms.double(0.5)
process.analyzeHiMassTau.RemoveJetOverlapWithTau2s            = cms.bool(False)
process.analyzeHiMassTau.JetTau2MatchingDeltaR                = cms.double(0.25)
process.analyzeHiMassTau.DoDiscrByFirstLeadingJet		= cms.bool(True)
process.analyzeHiMassTau.RecoFirstLeadingJetPt		= cms.double(15.0)
process.analyzeHiMassTau.RecoFirstLeadingJetEtaMinCut	= cms.double(2.1)
process.analyzeHiMassTau.RecoFirstLeadingJetEtaMaxCut	= cms.double(5.0)
process.analyzeHiMassTau.DoDiscrBySecondLeadingJet		= cms.bool(True)
process.analyzeHiMassTau.RecoSecondLeadingJetPt		= cms.double(15.0)
process.analyzeHiMassTau.RecoSecondLeadingJetEtaMinCut	= cms.double(2.1)
process.analyzeHiMassTau.RecoSecondLeadingJetEtaMaxCut	= cms.double(5.0)
process.analyzeHiMassTau.RemoveFirstLeadingJetOverlapWithMuon1s           = cms.bool(True)
process.analyzeHiMassTau.FirstLeadingJetMuon1MatchingDeltaR               = cms.double(0.4)
process.analyzeHiMassTau.RemoveFirstLeadingJetOverlapWithElectron1s       = cms.bool(False)
process.analyzeHiMassTau.FirstLeadingJetElectron1MatchingDeltaR           = cms.double(0.3)
process.analyzeHiMassTau.RemoveFirstLeadingJetOverlapWithTau1s            = cms.bool(False)
process.analyzeHiMassTau.FirstLeadingJetTau1MatchingDeltaR                = cms.double(0.25)
process.analyzeHiMassTau.RemoveSecondLeadingJetOverlapWithMuon1s           = cms.bool(True)
process.analyzeHiMassTau.SecondLeadingJetMuon1MatchingDeltaR               = cms.double(0.4)
process.analyzeHiMassTau.RemoveSecondLeadingJetOverlapWithElectron1s       = cms.bool(False)
process.analyzeHiMassTau.SecondLeadingJetElectron1MatchingDeltaR           = cms.double(0.3)
process.analyzeHiMassTau.RemoveSecondLeadingJetOverlapWithTau1s            = cms.bool(False)
process.analyzeHiMassTau.SecondLeadingJetTau1MatchingDeltaR                = cms.double(0.25)
process.analyzeHiMassTau.RemoveFirstLeadingJetOverlapWithMuon2s           = cms.bool(False)
process.analyzeHiMassTau.FirstLeadingJetMuon2MatchingDeltaR               = cms.double(0.3)
process.analyzeHiMassTau.RemoveFirstLeadingJetOverlapWithElectron2s       = cms.bool(False)
process.analyzeHiMassTau.FirstLeadingJetElectron2MatchingDeltaR           = cms.double(0.3)
process.analyzeHiMassTau.RemoveFirstLeadingJetOverlapWithTau2s            = cms.bool(False)
process.analyzeHiMassTau.FirstLeadingJetTau2MatchingDeltaR                = cms.double(0.3)
process.analyzeHiMassTau.RemoveSecondLeadingJetOverlapWithMuon2s           = cms.bool(False)
process.analyzeHiMassTau.SecondLeadingJetMuon2MatchingDeltaR               = cms.double(0.3)
process.analyzeHiMassTau.RemoveSecondLeadingJetOverlapWithElectron2s       = cms.bool(False)
process.analyzeHiMassTau.SecondLeadingJetElectron2MatchingDeltaR           = cms.double(0.3)
process.analyzeHiMassTau.RemoveSecondLeadingJetOverlapWithTau2s            = cms.bool(False)
process.analyzeHiMassTau.SecondLeadingJetTau2MatchingDeltaR                = cms.double(0.3)

    #-----Reco b-Jet Inputs
process.analyzeHiMassTau.RecoBJetEtaMinCut                    = cms.double(0.0)                            
process.analyzeHiMassTau.RecoBJetEtaMaxCut                    = cms.double(2.4)                            
process.analyzeHiMassTau.RecoBJetPtCut                        = cms.double(20.0)                           
process.analyzeHiMassTau.RemoveBJetOverlapWithMuon1s           = cms.bool(True)                            
process.analyzeHiMassTau.BJetMuon1MatchingDeltaR               = cms.double(0.4)                            
process.analyzeHiMassTau.RemoveBJetOverlapWithElectron1s       = cms.bool(False)                            
process.analyzeHiMassTau.BJetElectron1MatchingDeltaR           = cms.double(0.3)                            
process.analyzeHiMassTau.RemoveBJetOverlapWithTau1s            = cms.bool(False)                            
process.analyzeHiMassTau.BJetTau1MatchingDeltaR                = cms.double(0.3)                            
process.analyzeHiMassTau.RemoveBJetOverlapWithMuon2s           = cms.bool(False)
process.analyzeHiMassTau.BJetMuon2MatchingDeltaR               = cms.double(0.3)
process.analyzeHiMassTau.RemoveBJetOverlapWithElectron2s       = cms.bool(False)
process.analyzeHiMassTau.BJetElectron2MatchingDeltaR           = cms.double(0.3)
process.analyzeHiMassTau.RemoveBJetOverlapWithTau2s            = cms.bool(False)
process.analyzeHiMassTau.BJetTau2MatchingDeltaR                = cms.double(0.3)                            
process.analyzeHiMassTau.ApplyJetBTagging                    = cms.bool(False)                              
process.analyzeHiMassTau.bTagger = cms.untracked.string('combinedSecondaryVertexBJetTags')
process.analyzeHiMassTau.JetBTaggingCut                  = cms.double(0.679)

    #-----Vertex Inputs
process.analyzeHiMassTau.RecoVertexSource = cms.InputTag('offlinePrimaryVertices') 				# vertex collection
process.analyzeHiMassTau.RecoVertexMaxZposition = cms.double(20.0)						# vertex |z| < X
process.analyzeHiMassTau.RecoVertexMinTracks = cms.int32(2)						# vertex must have >= 2 "good" tracks used to reconstruct it
process.analyzeHiMassTau.RecoVertexTrackWeight = cms.double(0.5)						# weight used to define "good" tracks used to reconstruct vertex

    #-----Trigger Inputs
process.analyzeHiMassTau.RecoTriggerSource = cms.InputTag("TriggerResults","","HLT")			# trigger collection
process.analyzeHiMassTau.TriggerRequirements = cms.vstring('HLT_PFMHT150','HLT_PFMHT150_v1','HLT_PFMHT150_v2','HLT_PFMHT150_v3','HLT_PFMHT150_v4')  # trigger path name

    #-----Susy Topology Inputs
process.analyzeHiMassTau.DoSUSYDiscrByMHT = cms.bool(False)
process.analyzeHiMassTau.MhtCut = cms.double(250.0)
process.analyzeHiMassTau.DoSUSYDiscrByHT = cms.bool(False)
process.analyzeHiMassTau.HtCut = cms.double(250.0)
process.analyzeHiMassTau.DoSUSYDiscrByR1 = cms.bool(False)
process.analyzeHiMassTau.R1MinCut = cms.double(0.85)
process.analyzeHiMassTau.R1MaxCut = cms.double(999.0)
process.analyzeHiMassTau.DoSUSYDiscrByR2 = cms.bool(False)
process.analyzeHiMassTau.R2MinCut = cms.double(0.0)
process.analyzeHiMassTau.R2MaxCut = cms.double(3.6)
process.analyzeHiMassTau.DoSUSYDiscrByAlpha = cms.bool(False)
process.analyzeHiMassTau.AlphaMinCut = cms.double(0.5)
process.analyzeHiMassTau.AlphaMaxCut = cms.double(9999999999.9)
process.analyzeHiMassTau.DoSUSYDiscrByDphi1 = cms.bool(False)
process.analyzeHiMassTau.Dphi1MinCut = cms.double(0.9)
process.analyzeHiMassTau.Dphi1MaxCut = cms.double(999.9)
process.analyzeHiMassTau.DoSUSYDiscrByDphi2 = cms.bool(False)
process.analyzeHiMassTau.Dphi2MinCut = cms.double(0.5)                                                     
process.analyzeHiMassTau.Dphi2MaxCut = cms.double(9999.5)                                               
process.analyzeHiMassTau.DoSUSYDiscrByLeadDiJetMass = cms.bool(False)
process.analyzeHiMassTau.LeadDiJetMinMassCut = cms.double(650.0)
process.analyzeHiMassTau.LeadDiJetMaxMassCut = cms.double(9999.0)
process.analyzeHiMassTau.DoSUSYDiscrByLeadDiJetPt = cms.bool(False)
process.analyzeHiMassTau.LeadDiJetMinPtCut = cms.double(0.5)
process.analyzeHiMassTau.LeadDiJetMaxPtCut = cms.double(0.5)
process.analyzeHiMassTau.DoSUSYDiscrByLeadDiJetDeltaEta = cms.bool(False)
process.analyzeHiMassTau.LeadDiJetMinDeltaEtaCut = cms.double(4.2)
process.analyzeHiMassTau.LeadDiJetMaxDeltaEtaCut = cms.double(9999.0)

    #-----Topology Inputs
process.analyzeHiMassTau.RecoMetSource = cms.InputTag('patPFType1Type2Type0METs')		
process.analyzeHiMassTau.DoDiscrByMet = cms.bool(False) 				
process.analyzeHiMassTau.RecoMetCut = cms.double(30.0) 					
process.analyzeHiMassTau.DoDiMuonDiscrByDeltaR = cms.bool(True)
process.analyzeHiMassTau.DiMuonDeltaRCut = cms.double(0.3)
process.analyzeHiMassTau.DiMuonDiscrByOSLSType = cms.string('NONE')
process.analyzeHiMassTau.DoDiMuonDiscrByCosDphi = cms.bool(False)
process.analyzeHiMassTau.DiMuonCosDphiMaxCut = cms.double(-0.95)
process.analyzeHiMassTau.DiMuonCosDphiMinCut = cms.double(-1.00)
process.analyzeHiMassTau.DoDiscrByDiMuonMassReco = cms.bool(False)
process.analyzeHiMassTau.UseVectorSumOfDiMuonProductsAndMetMassReco = cms.bool(False)
process.analyzeHiMassTau.UseCollinerApproxDiMuonMassReco = cms.bool(False)
process.analyzeHiMassTau.DiMuonMassMinCut = cms.double(150.0)
process.analyzeHiMassTau.DiMuonMassMaxCut = cms.double(1000.0)
process.analyzeHiMassTau.DoDiMuonDiscrByCDFzeta2D = cms.bool(False)
process.analyzeHiMassTau.DiMuonPZetaCutCoefficient = cms.double(1.0)
process.analyzeHiMassTau.DiMuonPZetaVisCutCoefficient = cms.double(-0.875)
process.analyzeHiMassTau.DiMuonCDFzeta2DCutValue = cms.double(-7.00)
process.analyzeHiMassTau.DoDiMuonDiscrByDeltaPtDivSumPt = cms.bool(False)
process.analyzeHiMassTau.DiMuonDeltaPtDivSumPtMinCutValue = cms.double(0.1)
process.analyzeHiMassTau.DiMuonDeltaPtDivSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.DoDiMuonDiscrByDeltaPt = cms.bool(False)
process.analyzeHiMassTau.DiMuonDeltaPtMinCutValue = cms.double(30.0)
process.analyzeHiMassTau.DiMuonDeltaPtMaxCutValue = cms.double(9999.0)
process.analyzeHiMassTau.DoDiTauDiscrByDeltaR = cms.bool(True) 				
process.analyzeHiMassTau.DiTauDeltaRCut = cms.double(0.3)	 			
process.analyzeHiMassTau.DiTauDiscrByOSLSType = cms.string('NONE')		 	
process.analyzeHiMassTau.UseTauSeedTrackForDiTauDiscrByOSLS = cms.bool(False) 		
process.analyzeHiMassTau.DoDiTauDiscrByCosDphi = cms.bool(False) 			
process.analyzeHiMassTau.DiTauCosDphiMaxCut = cms.double(-0.95) 			
process.analyzeHiMassTau.DiTauCosDphiMinCut = cms.double(-1.00) 			
process.analyzeHiMassTau.DoDiscrByDiTauMassReco = cms.bool(False) 				
process.analyzeHiMassTau.UseVectorSumOfDiTauProductsAndMetMassReco = cms.bool(False) 	
process.analyzeHiMassTau.UseCollinerApproxDiTauMassReco = cms.bool(False) 			
process.analyzeHiMassTau.DiTauMassMinCut = cms.double(150.0) 				
process.analyzeHiMassTau.DiTauMassMaxCut = cms.double(1000.0) 				
process.analyzeHiMassTau.DoDiTauDiscrByCDFzeta2D = cms.bool(False)			
process.analyzeHiMassTau.DiTauPZetaCutCoefficient = cms.double(1.0)				
process.analyzeHiMassTau.DiTauPZetaVisCutCoefficient = cms.double(-0.875)			
process.analyzeHiMassTau.DiTauCDFzeta2DCutValue = cms.double(-7.00)				
process.analyzeHiMassTau.DoDiTauDiscrByDeltaPtDivSumPt = cms.bool(False)		
process.analyzeHiMassTau.DiTauDeltaPtDivSumPtMinCutValue = cms.double(0.1)		
process.analyzeHiMassTau.DiTauDeltaPtDivSumPtMaxCutValue = cms.double(1.0)		
process.analyzeHiMassTau.DoDiTauDiscrByDeltaPt = cms.bool(False)			
process.analyzeHiMassTau.DiTauDeltaPtMinCutValue = cms.double(30.0)			
process.analyzeHiMassTau.DiTauDeltaPtMaxCutValue = cms.double(9999.0)			
process.analyzeHiMassTau.DoDiElectronDiscrByDeltaR = cms.bool(True)
process.analyzeHiMassTau.DiElectronDeltaRCut = cms.double(0.3)
process.analyzeHiMassTau.DiElectronDiscrByOSLSType = cms.string('NONE')
process.analyzeHiMassTau.DoDiElectronDiscrByCosDphi = cms.bool(False)
process.analyzeHiMassTau.DiElectronCosDphiMaxCut = cms.double(-0.95)
process.analyzeHiMassTau.DiElectronCosDphiMinCut = cms.double(-1.00)
process.analyzeHiMassTau.DoDiscrByDiElectronMassReco = cms.bool(False)
process.analyzeHiMassTau.UseVectorSumOfDiElectronProductsAndMetMassReco = cms.bool(False)
process.analyzeHiMassTau.UseCollinerApproxDiElectronMassReco = cms.bool(False)
process.analyzeHiMassTau.DiElectronMassMinCut = cms.double(150.0)
process.analyzeHiMassTau.DiElectronMassMaxCut = cms.double(1000.0)
process.analyzeHiMassTau.DoDiElectronDiscrByCDFzeta2D = cms.bool(False)
process.analyzeHiMassTau.DiElectronPZetaCutCoefficient = cms.double(1.0)
process.analyzeHiMassTau.DiElectronPZetaVisCutCoefficient = cms.double(-0.875)
process.analyzeHiMassTau.DiElectronCDFzeta2DCutValue = cms.double(-7.00)
process.analyzeHiMassTau.DoDiElectronDiscrByDeltaPtDivSumPt = cms.bool(False)
process.analyzeHiMassTau.DiElectronDeltaPtDivSumPtMinCutValue = cms.double(0.1)
process.analyzeHiMassTau.DiElectronDeltaPtDivSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.DoDiElectronDiscrByDeltaPt = cms.bool(False)
process.analyzeHiMassTau.DiElectronDeltaPtMinCutValue = cms.double(30.0)
process.analyzeHiMassTau.DiElectronDeltaPtMaxCutValue = cms.double(9999.0)
process.analyzeHiMassTau.DoMuon1Tau1DiscrByDeltaR = cms.bool(True)
process.analyzeHiMassTau.Muon1Tau1DeltaRCut = cms.double(0.3)
process.analyzeHiMassTau.Muon1Tau1DiscrByOSLSType = cms.string('NONE')
process.analyzeHiMassTau.UseTauSeedTrackForMuon1Tau1DiscrByOSLS = cms.bool(False)
process.analyzeHiMassTau.DoMuon1Tau1DiscrByCosDphi = cms.bool(False)
process.analyzeHiMassTau.Muon1Tau1CosDphiMaxCut = cms.double(-0.95)
process.analyzeHiMassTau.Muon1Tau1CosDphiMinCut = cms.double(-1.00)
process.analyzeHiMassTau.DoDiscrByMuon1Tau1MassReco = cms.bool(False)
process.analyzeHiMassTau.UseVectorSumOfMuon1Tau1ProductsAndMetMassReco = cms.bool(False)
process.analyzeHiMassTau.UseCollinerApproxMuon1Tau1MassReco = cms.bool(False)
process.analyzeHiMassTau.Muon1Tau1MassMinCut = cms.double(150.0)
process.analyzeHiMassTau.Muon1Tau1MassMaxCut = cms.double(1000.0)
process.analyzeHiMassTau.DoMuon1Tau1DiscrByCDFzeta2D = cms.bool(False)
process.analyzeHiMassTau.Muon1Tau1PZetaCutCoefficient = cms.double(1.0)
process.analyzeHiMassTau.Muon1Tau1PZetaVisCutCoefficient = cms.double(-0.875)
process.analyzeHiMassTau.Muon1Tau1CDFzeta2DCutValue = cms.double(-7.00)
process.analyzeHiMassTau.DoMuon1Tau1DiscrByDeltaPtDivSumPt = cms.bool(False)
process.analyzeHiMassTau.Muon1Tau1DeltaPtDivSumPtMinCutValue = cms.double(0.1)
process.analyzeHiMassTau.Muon1Tau1DeltaPtDivSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.DoMuon1Tau1DiscrByDeltaPt = cms.bool(False)
process.analyzeHiMassTau.Muon1Tau1DeltaPtMinCutValue = cms.double(30.0)
process.analyzeHiMassTau.Muon1Tau1DeltaPtMaxCutValue = cms.double(9999.0)
process.analyzeHiMassTau.DoMuon1Tau2DiscrByDeltaR = cms.bool(True)
process.analyzeHiMassTau.Muon1Tau2DeltaRCut = cms.double(0.3)
process.analyzeHiMassTau.Muon1Tau2DiscrByOSLSType = cms.string('NONE')
process.analyzeHiMassTau.UseTauSeedTrackForMuon1Tau2DiscrByOSLS = cms.bool(False)
process.analyzeHiMassTau.DoMuon1Tau2DiscrByCosDphi = cms.bool(False)
process.analyzeHiMassTau.Muon1Tau2CosDphiMaxCut = cms.double(-0.95)
process.analyzeHiMassTau.Muon1Tau2CosDphiMinCut = cms.double(-1.00)
process.analyzeHiMassTau.DoDiscrByMuon1Tau2MassReco = cms.bool(False)
process.analyzeHiMassTau.UseVectorSumOfMuon1Tau2ProductsAndMetMassReco = cms.bool(False)
process.analyzeHiMassTau.UseCollinerApproxMuon1Tau2MassReco = cms.bool(False)
process.analyzeHiMassTau.Muon1Tau2MassMinCut = cms.double(150.0)
process.analyzeHiMassTau.Muon1Tau2MassMaxCut = cms.double(1000.0)
process.analyzeHiMassTau.DoMuon1Tau2DiscrByCDFzeta2D = cms.bool(False)
process.analyzeHiMassTau.Muon1Tau2PZetaCutCoefficient = cms.double(1.0)
process.analyzeHiMassTau.Muon1Tau2PZetaVisCutCoefficient = cms.double(-0.875)
process.analyzeHiMassTau.Muon1Tau2CDFzeta2DCutValue = cms.double(-7.00)
process.analyzeHiMassTau.DoMuon1Tau2DiscrByDeltaPtDivSumPt = cms.bool(False)
process.analyzeHiMassTau.Muon1Tau2DeltaPtDivSumPtMinCutValue = cms.double(0.1)
process.analyzeHiMassTau.Muon1Tau2DeltaPtDivSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.DoMuon1Tau2DiscrByDeltaPt = cms.bool(False)
process.analyzeHiMassTau.Muon1Tau2DeltaPtMinCutValue = cms.double(30.0)
process.analyzeHiMassTau.Muon1Tau2DeltaPtMaxCutValue = cms.double(9999.0)
process.analyzeHiMassTau.DoMuon2Tau1DiscrByDeltaR = cms.bool(True)
process.analyzeHiMassTau.Muon2Tau1DeltaRCut = cms.double(0.3)
process.analyzeHiMassTau.Muon2Tau1DiscrByOSLSType = cms.string('NONE')
process.analyzeHiMassTau.UseTauSeedTrackForMuon2Tau1DiscrByOSLS = cms.bool(False)
process.analyzeHiMassTau.DoMuon2Tau1DiscrByCosDphi = cms.bool(False)
process.analyzeHiMassTau.Muon2Tau1CosDphiMaxCut = cms.double(-0.95)
process.analyzeHiMassTau.Muon2Tau1CosDphiMinCut = cms.double(-1.00)
process.analyzeHiMassTau.DoDiscrByMuon2Tau1MassReco = cms.bool(False)
process.analyzeHiMassTau.UseVectorSumOfMuon2Tau1ProductsAndMetMassReco = cms.bool(False)
process.analyzeHiMassTau.UseCollinerApproxMuon2Tau1MassReco = cms.bool(False)
process.analyzeHiMassTau.Muon2Tau1MassMinCut = cms.double(150.0)
process.analyzeHiMassTau.Muon2Tau1MassMaxCut = cms.double(1000.0)
process.analyzeHiMassTau.DoMuon2Tau1DiscrByCDFzeta2D = cms.bool(False)
process.analyzeHiMassTau.Muon2Tau1PZetaCutCoefficient = cms.double(1.0)
process.analyzeHiMassTau.Muon2Tau1PZetaVisCutCoefficient = cms.double(-0.875)
process.analyzeHiMassTau.Muon2Tau1CDFzeta2DCutValue = cms.double(-7.00)
process.analyzeHiMassTau.DoMuon2Tau1DiscrByDeltaPtDivSumPt = cms.bool(False)
process.analyzeHiMassTau.Muon2Tau1DeltaPtDivSumPtMinCutValue = cms.double(0.1)
process.analyzeHiMassTau.Muon2Tau1DeltaPtDivSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.DoMuon2Tau1DiscrByDeltaPt = cms.bool(False)
process.analyzeHiMassTau.Muon2Tau1DeltaPtMinCutValue = cms.double(30.0)
process.analyzeHiMassTau.Muon2Tau1DeltaPtMaxCutValue = cms.double(9999.0)
process.analyzeHiMassTau.DoMuon2Tau2DiscrByDeltaR = cms.bool(True)
process.analyzeHiMassTau.Muon2Tau2DeltaRCut = cms.double(0.3)
process.analyzeHiMassTau.Muon2Tau2DiscrByOSLSType = cms.string('NONE')
process.analyzeHiMassTau.UseTauSeedTrackForMuon2Tau2DiscrByOSLS = cms.bool(False)
process.analyzeHiMassTau.DoMuon2Tau2DiscrByCosDphi = cms.bool(False)
process.analyzeHiMassTau.Muon2Tau2CosDphiMaxCut = cms.double(-0.95)
process.analyzeHiMassTau.Muon2Tau2CosDphiMinCut = cms.double(-1.00)
process.analyzeHiMassTau.DoDiscrByMuon2Tau2MassReco = cms.bool(False)
process.analyzeHiMassTau.UseVectorSumOfMuon2Tau2ProductsAndMetMassReco = cms.bool(False)
process.analyzeHiMassTau.UseCollinerApproxMuon2Tau2MassReco = cms.bool(False)
process.analyzeHiMassTau.Muon2Tau2MassMinCut = cms.double(150.0)
process.analyzeHiMassTau.Muon2Tau2MassMaxCut = cms.double(1000.0)
process.analyzeHiMassTau.DoMuon2Tau2DiscrByCDFzeta2D = cms.bool(False)
process.analyzeHiMassTau.Muon2Tau2PZetaCutCoefficient = cms.double(1.0)
process.analyzeHiMassTau.Muon2Tau2PZetaVisCutCoefficient = cms.double(-0.875)
process.analyzeHiMassTau.Muon2Tau2CDFzeta2DCutValue = cms.double(-7.00)
process.analyzeHiMassTau.DoMuon2Tau2DiscrByDeltaPtDivSumPt = cms.bool(False)
process.analyzeHiMassTau.Muon2Tau2DeltaPtDivSumPtMinCutValue = cms.double(0.1)
process.analyzeHiMassTau.Muon2Tau2DeltaPtDivSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.DoMuon2Tau2DiscrByDeltaPt = cms.bool(False)
process.analyzeHiMassTau.Muon2Tau2DeltaPtMinCutValue = cms.double(30.0)
process.analyzeHiMassTau.Muon2Tau2DeltaPtMaxCutValue = cms.double(9999.0)
process.analyzeHiMassTau.DoElectron1Tau1DiscrByDeltaR = cms.bool(True)
process.analyzeHiMassTau.Electron1Tau1DeltaRCut = cms.double(0.3)
process.analyzeHiMassTau.Electron1Tau1DiscrByOSLSType = cms.string('NONE')
process.analyzeHiMassTau.UseTauSeedTrackForElectron1Tau1DiscrByOSLS = cms.bool(False)
process.analyzeHiMassTau.DoElectron1Tau1DiscrByCosDphi = cms.bool(False)
process.analyzeHiMassTau.Electron1Tau1CosDphiMaxCut = cms.double(-0.95)
process.analyzeHiMassTau.Electron1Tau1CosDphiMinCut = cms.double(-1.00)
process.analyzeHiMassTau.DoDiscrByElectron1Tau1MassReco = cms.bool(False)
process.analyzeHiMassTau.UseVectorSumOfElectron1Tau1ProductsAndMetMassReco = cms.bool(False)
process.analyzeHiMassTau.UseCollinerApproxElectron1Tau1MassReco = cms.bool(False)
process.analyzeHiMassTau.Electron1Tau1MassMinCut = cms.double(150.0)
process.analyzeHiMassTau.Electron1Tau1MassMaxCut = cms.double(1000.0)
process.analyzeHiMassTau.DoElectron1Tau1DiscrByCDFzeta2D = cms.bool(False)
process.analyzeHiMassTau.Electron1Tau1PZetaCutCoefficient = cms.double(1.0)
process.analyzeHiMassTau.Electron1Tau1PZetaVisCutCoefficient = cms.double(-0.875)
process.analyzeHiMassTau.Electron1Tau1CDFzeta2DCutValue = cms.double(-7.00)
process.analyzeHiMassTau.DoElectron1Tau1DiscrByDeltaPtDivSumPt = cms.bool(False)
process.analyzeHiMassTau.Electron1Tau1DeltaPtDivSumPtMinCutValue = cms.double(0.1)
process.analyzeHiMassTau.Electron1Tau1DeltaPtDivSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.DoElectron1Tau1DiscrByDeltaPt = cms.bool(False)
process.analyzeHiMassTau.Electron1Tau1DeltaPtMinCutValue = cms.double(30.0)
process.analyzeHiMassTau.Electron1Tau1DeltaPtMaxCutValue = cms.double(9999.0)
process.analyzeHiMassTau.DoElectron1Tau2DiscrByDeltaR = cms.bool(True)
process.analyzeHiMassTau.Electron1Tau2DeltaRCut = cms.double(0.3)
process.analyzeHiMassTau.Electron1Tau2DiscrByOSLSType = cms.string('NONE')
process.analyzeHiMassTau.UseTauSeedTrackForElectron1Tau2DiscrByOSLS = cms.bool(False)
process.analyzeHiMassTau.DoElectron1Tau2DiscrByCosDphi = cms.bool(False)
process.analyzeHiMassTau.Electron1Tau2CosDphiMaxCut = cms.double(-0.95)
process.analyzeHiMassTau.Electron1Tau2CosDphiMinCut = cms.double(-1.00)
process.analyzeHiMassTau.DoDiscrByElectron1Tau2MassReco = cms.bool(False)
process.analyzeHiMassTau.UseVectorSumOfElectron1Tau2ProductsAndMetMassReco = cms.bool(False)
process.analyzeHiMassTau.UseCollinerApproxElectron1Tau2MassReco = cms.bool(False)
process.analyzeHiMassTau.Electron1Tau2MassMinCut = cms.double(150.0)
process.analyzeHiMassTau.Electron1Tau2MassMaxCut = cms.double(1000.0)
process.analyzeHiMassTau.DoElectron1Tau2DiscrByCDFzeta2D = cms.bool(False)
process.analyzeHiMassTau.Electron1Tau2PZetaCutCoefficient = cms.double(1.0)
process.analyzeHiMassTau.Electron1Tau2PZetaVisCutCoefficient = cms.double(-0.875)
process.analyzeHiMassTau.Electron1Tau2CDFzeta2DCutValue = cms.double(-7.00)
process.analyzeHiMassTau.DoElectron1Tau2DiscrByDeltaPtDivSumPt = cms.bool(False)
process.analyzeHiMassTau.Electron1Tau2DeltaPtDivSumPtMinCutValue = cms.double(0.1)
process.analyzeHiMassTau.Electron1Tau2DeltaPtDivSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.DoElectron1Tau2DiscrByDeltaPt = cms.bool(False)
process.analyzeHiMassTau.Electron1Tau2DeltaPtMinCutValue = cms.double(30.0)
process.analyzeHiMassTau.Electron1Tau2DeltaPtMaxCutValue = cms.double(9999.0)
process.analyzeHiMassTau.DoElectron2Tau1DiscrByDeltaR = cms.bool(True)
process.analyzeHiMassTau.Electron2Tau1DeltaRCut = cms.double(0.3)
process.analyzeHiMassTau.Electron2Tau1DiscrByOSLSType = cms.string('NONE')
process.analyzeHiMassTau.UseTauSeedTrackForElectron2Tau1DiscrByOSLS = cms.bool(False)
process.analyzeHiMassTau.DoElectron2Tau1DiscrByCosDphi = cms.bool(False)
process.analyzeHiMassTau.Electron2Tau1CosDphiMaxCut = cms.double(-0.95)
process.analyzeHiMassTau.Electron2Tau1CosDphiMinCut = cms.double(-1.00)
process.analyzeHiMassTau.DoDiscrByElectron2Tau1MassReco = cms.bool(False)
process.analyzeHiMassTau.UseVectorSumOfElectron2Tau1ProductsAndMetMassReco = cms.bool(False)
process.analyzeHiMassTau.UseCollinerApproxElectron2Tau1MassReco = cms.bool(False)
process.analyzeHiMassTau.Electron2Tau1MassMinCut = cms.double(150.0)
process.analyzeHiMassTau.Electron2Tau1MassMaxCut = cms.double(1000.0)
process.analyzeHiMassTau.DoElectron2Tau1DiscrByCDFzeta2D = cms.bool(False)
process.analyzeHiMassTau.Electron2Tau1PZetaCutCoefficient = cms.double(1.0)
process.analyzeHiMassTau.Electron2Tau1PZetaVisCutCoefficient = cms.double(-0.875)
process.analyzeHiMassTau.Electron2Tau1CDFzeta2DCutValue = cms.double(-7.00)
process.analyzeHiMassTau.DoElectron2Tau1DiscrByDeltaPtDivSumPt = cms.bool(False)
process.analyzeHiMassTau.Electron2Tau1DeltaPtDivSumPtMinCutValue = cms.double(0.1)
process.analyzeHiMassTau.Electron2Tau1DeltaPtDivSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.DoElectron2Tau1DiscrByDeltaPt = cms.bool(False)
process.analyzeHiMassTau.Electron2Tau1DeltaPtMinCutValue = cms.double(30.0)
process.analyzeHiMassTau.Electron2Tau1DeltaPtMaxCutValue = cms.double(9999.0)
process.analyzeHiMassTau.DoElectron2Tau2DiscrByDeltaR = cms.bool(True)
process.analyzeHiMassTau.Electron2Tau2DeltaRCut = cms.double(0.3)
process.analyzeHiMassTau.Electron2Tau2DiscrByOSLSType = cms.string('NONE')
process.analyzeHiMassTau.UseTauSeedTrackForElectron2Tau2DiscrByOSLS = cms.bool(False)
process.analyzeHiMassTau.DoElectron2Tau2DiscrByCosDphi = cms.bool(False)
process.analyzeHiMassTau.Electron2Tau2CosDphiMaxCut = cms.double(-0.95)
process.analyzeHiMassTau.Electron2Tau2CosDphiMinCut = cms.double(-1.00)
process.analyzeHiMassTau.DoDiscrByElectron2Tau2MassReco = cms.bool(False)
process.analyzeHiMassTau.UseVectorSumOfElectron2Tau2ProductsAndMetMassReco = cms.bool(False)
process.analyzeHiMassTau.UseCollinerApproxElectron2Tau2MassReco = cms.bool(False)
process.analyzeHiMassTau.Electron2Tau2MassMinCut = cms.double(150.0)
process.analyzeHiMassTau.Electron2Tau2MassMaxCut = cms.double(1000.0)
process.analyzeHiMassTau.DoElectron2Tau2DiscrByCDFzeta2D = cms.bool(False)
process.analyzeHiMassTau.Electron2Tau2PZetaCutCoefficient = cms.double(1.0)
process.analyzeHiMassTau.Electron2Tau2PZetaVisCutCoefficient = cms.double(-0.875)
process.analyzeHiMassTau.Electron2Tau2CDFzeta2DCutValue = cms.double(-7.00)
process.analyzeHiMassTau.DoElectron2Tau2DiscrByDeltaPtDivSumPt = cms.bool(False)
process.analyzeHiMassTau.Electron2Tau2DeltaPtDivSumPtMinCutValue = cms.double(0.1)
process.analyzeHiMassTau.Electron2Tau2DeltaPtDivSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.DoElectron2Tau2DiscrByDeltaPt = cms.bool(False)
process.analyzeHiMassTau.Electron2Tau2DeltaPtMinCutValue = cms.double(30.0)
process.analyzeHiMassTau.Electron2Tau2DeltaPtMaxCutValue = cms.double(9999.0)
process.analyzeHiMassTau.DoElectron1Muon1DiscrByDeltaR = cms.bool(True)
process.analyzeHiMassTau.Electron1Muon1DeltaRCut = cms.double(0.3)
process.analyzeHiMassTau.Electron1Muon1DiscrByOSLSType = cms.string('NONE')
process.analyzeHiMassTau.DoElectron1Muon1DiscrByCosDphi = cms.bool(False)
process.analyzeHiMassTau.Electron1Muon1CosDphiMaxCut = cms.double(-0.95)
process.analyzeHiMassTau.Electron1Muon1CosDphiMinCut = cms.double(-1.00)
process.analyzeHiMassTau.DoDiscrByElectron1Muon1MassReco = cms.bool(False)
process.analyzeHiMassTau.UseVectorSumOfElectron1Muon1ProductsAndMetMassReco = cms.bool(False)
process.analyzeHiMassTau.UseCollinerApproxElectron1Muon1MassReco = cms.bool(False)
process.analyzeHiMassTau.Electron1Muon1MassMinCut = cms.double(150.0)
process.analyzeHiMassTau.Electron1Muon1MassMaxCut = cms.double(1000.0)
process.analyzeHiMassTau.DoElectron1Muon1DiscrByCDFzeta2D = cms.bool(False)
process.analyzeHiMassTau.Electron1Muon1PZetaCutCoefficient = cms.double(1.0)
process.analyzeHiMassTau.Electron1Muon1PZetaVisCutCoefficient = cms.double(-0.875)
process.analyzeHiMassTau.Electron1Muon1CDFzeta2DCutValue = cms.double(-7.00)
process.analyzeHiMassTau.DoElectron1Muon1DiscrByDeltaPtDivSumPt = cms.bool(False)
process.analyzeHiMassTau.Electron1Muon1DeltaPtDivSumPtMinCutValue = cms.double(0.1)
process.analyzeHiMassTau.Electron1Muon1DeltaPtDivSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.DoElectron1Muon1DiscrByDeltaPt = cms.bool(False)
process.analyzeHiMassTau.Electron1Muon1DeltaPtMinCutValue = cms.double(30.0)
process.analyzeHiMassTau.Electron1Muon1DeltaPtMaxCutValue = cms.double(9999.0)
process.analyzeHiMassTau.DoElectron1Muon2DiscrByDeltaR = cms.bool(True)
process.analyzeHiMassTau.Electron1Muon2DeltaRCut = cms.double(0.3)
process.analyzeHiMassTau.Electron1Muon2DiscrByOSLSType = cms.string('NONE')
process.analyzeHiMassTau.DoElectron1Muon2DiscrByCosDphi = cms.bool(False)
process.analyzeHiMassTau.Electron1Muon2CosDphiMaxCut = cms.double(-0.95)
process.analyzeHiMassTau.Electron1Muon2CosDphiMinCut = cms.double(-1.00)
process.analyzeHiMassTau.DoDiscrByElectron1Muon2MassReco = cms.bool(False)
process.analyzeHiMassTau.UseVectorSumOfElectron1Muon2ProductsAndMetMassReco = cms.bool(False)
process.analyzeHiMassTau.UseCollinerApproxElectron1Muon2MassReco = cms.bool(False)
process.analyzeHiMassTau.Electron1Muon2MassMinCut = cms.double(150.0)
process.analyzeHiMassTau.Electron1Muon2MassMaxCut = cms.double(1000.0)
process.analyzeHiMassTau.DoElectron1Muon2DiscrByCDFzeta2D = cms.bool(False)
process.analyzeHiMassTau.Electron1Muon2PZetaCutCoefficient = cms.double(1.0)
process.analyzeHiMassTau.Electron1Muon2PZetaVisCutCoefficient = cms.double(-0.875)
process.analyzeHiMassTau.Electron1Muon2CDFzeta2DCutValue = cms.double(-7.00)
process.analyzeHiMassTau.DoElectron1Muon2DiscrByDeltaPtDivSumPt = cms.bool(False)
process.analyzeHiMassTau.Electron1Muon2DeltaPtDivSumPtMinCutValue = cms.double(0.1)
process.analyzeHiMassTau.Electron1Muon2DeltaPtDivSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.DoElectron1Muon2DiscrByDeltaPt = cms.bool(False)
process.analyzeHiMassTau.Electron1Muon2DeltaPtMinCutValue = cms.double(30.0)
process.analyzeHiMassTau.Electron1Muon2DeltaPtMaxCutValue = cms.double(9999.0)
process.analyzeHiMassTau.DoElectron2Muon1DiscrByDeltaR = cms.bool(True)
process.analyzeHiMassTau.Electron2Muon1DeltaRCut = cms.double(0.3)
process.analyzeHiMassTau.Electron2Muon1DiscrByOSLSType = cms.string('NONE')
process.analyzeHiMassTau.DoElectron2Muon1DiscrByCosDphi = cms.bool(False)
process.analyzeHiMassTau.Electron2Muon1CosDphiMaxCut = cms.double(-0.95)
process.analyzeHiMassTau.Electron2Muon1CosDphiMinCut = cms.double(-1.00)
process.analyzeHiMassTau.DoDiscrByElectron2Muon1MassReco = cms.bool(False)
process.analyzeHiMassTau.UseVectorSumOfElectron2Muon1ProductsAndMetMassReco = cms.bool(False)
process.analyzeHiMassTau.UseCollinerApproxElectron2Muon1MassReco = cms.bool(False)
process.analyzeHiMassTau.Electron2Muon1MassMinCut = cms.double(150.0)
process.analyzeHiMassTau.Electron2Muon1MassMaxCut = cms.double(1000.0)
process.analyzeHiMassTau.DoElectron2Muon1DiscrByCDFzeta2D = cms.bool(False)
process.analyzeHiMassTau.Electron2Muon1PZetaCutCoefficient = cms.double(1.0)
process.analyzeHiMassTau.Electron2Muon1PZetaVisCutCoefficient = cms.double(-0.875)
process.analyzeHiMassTau.Electron2Muon1CDFzeta2DCutValue = cms.double(-7.00)
process.analyzeHiMassTau.DoElectron2Muon1DiscrByDeltaPtDivSumPt = cms.bool(False)
process.analyzeHiMassTau.Electron2Muon1DeltaPtDivSumPtMinCutValue = cms.double(0.1)
process.analyzeHiMassTau.Electron2Muon1DeltaPtDivSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.DoElectron2Muon1DiscrByDeltaPt = cms.bool(False)
process.analyzeHiMassTau.Electron2Muon1DeltaPtMinCutValue = cms.double(30.0)
process.analyzeHiMassTau.Electron2Muon1DeltaPtMaxCutValue = cms.double(9999.0)
process.analyzeHiMassTau.DoElectron2Muon2DiscrByDeltaR = cms.bool(True)
process.analyzeHiMassTau.Electron2Muon2DeltaRCut = cms.double(0.3)
process.analyzeHiMassTau.Electron2Muon2DiscrByOSLSType = cms.string('NONE')
process.analyzeHiMassTau.DoElectron2Muon2DiscrByCosDphi = cms.bool(False)
process.analyzeHiMassTau.Electron2Muon2CosDphiMaxCut = cms.double(-0.95)
process.analyzeHiMassTau.Electron2Muon2CosDphiMinCut = cms.double(-1.00)
process.analyzeHiMassTau.DoDiscrByElectron2Muon2MassReco = cms.bool(False)
process.analyzeHiMassTau.UseVectorSumOfElectron2Muon2ProductsAndMetMassReco = cms.bool(False)
process.analyzeHiMassTau.UseCollinerApproxElectron2Muon2MassReco = cms.bool(False)
process.analyzeHiMassTau.Electron2Muon2MassMinCut = cms.double(150.0)
process.analyzeHiMassTau.Electron2Muon2MassMaxCut = cms.double(1000.0)
process.analyzeHiMassTau.DoElectron2Muon2DiscrByCDFzeta2D = cms.bool(False)
process.analyzeHiMassTau.Electron2Muon2PZetaCutCoefficient = cms.double(1.0)
process.analyzeHiMassTau.Electron2Muon2PZetaVisCutCoefficient = cms.double(-0.875)
process.analyzeHiMassTau.Electron2Muon2CDFzeta2DCutValue = cms.double(-7.00)
process.analyzeHiMassTau.DoElectron2Muon2DiscrByDeltaPtDivSumPt = cms.bool(False)
process.analyzeHiMassTau.Electron2Muon2DeltaPtDivSumPtMinCutValue = cms.double(0.1)
process.analyzeHiMassTau.Electron2Muon2DeltaPtDivSumPtMaxCutValue = cms.double(1.0)
process.analyzeHiMassTau.DoElectron2Muon2DiscrByDeltaPt = cms.bool(False)
process.analyzeHiMassTau.Electron2Muon2DeltaPtMinCutValue = cms.double(30.0)
process.analyzeHiMassTau.Electron2Muon2DeltaPtMaxCutValue = cms.double(9999.0)
process.analyzeHiMassTau.DoDiscrByMuon1MetDphi = cms.bool(False)				
process.analyzeHiMassTau.Muon1MetDphiMinCut = cms.double(1.30)				
process.analyzeHiMassTau.Muon1MetDphiMaxCut = cms.double(3.15)				
process.analyzeHiMassTau.DoDiscrByMuon2MetDphi = cms.bool(False)				
process.analyzeHiMassTau.Muon2MetDphiMinCut = cms.double(1.30)				
process.analyzeHiMassTau.Muon2MetDphiMaxCut = cms.double(3.15)				
process.analyzeHiMassTau.DoDiscrByElectron1MetDphi = cms.bool(False)				
process.analyzeHiMassTau.Electron1MetDphiMinCut = cms.double(1.30)				
process.analyzeHiMassTau.Electron1MetDphiMaxCut = cms.double(3.15)				
process.analyzeHiMassTau.DoDiscrByElectron2MetDphi = cms.bool(False)				
process.analyzeHiMassTau.Electron2MetDphiMinCut = cms.double(1.30)				
process.analyzeHiMassTau.Electron2MetDphiMaxCut = cms.double(3.15)				
process.analyzeHiMassTau.DoDiscrByTau1MetDphi = cms.bool(False)				
process.analyzeHiMassTau.Tau1MetDphiMinCut = cms.double(1.30)				
process.analyzeHiMassTau.Tau1MetDphiMaxCut = cms.double(3.15)				
process.analyzeHiMassTau.DoDiscrByTau2MetDphi = cms.bool(False)				
process.analyzeHiMassTau.Tau2MetDphiMinCut = cms.double(1.30)				
process.analyzeHiMassTau.Tau2MetDphiMaxCut = cms.double(3.15)				
process.analyzeHiMassTau.DoDiscrByMuon1MetMt = cms.bool(False)
process.analyzeHiMassTau.Muon1MetMtMinCut = cms.double(0.0)
process.analyzeHiMassTau.Muon1MetMtMaxCut = cms.double(40.0)
process.analyzeHiMassTau.DoDiscrByMuon2MetMt = cms.bool(False)
process.analyzeHiMassTau.Muon2MetMtMinCut = cms.double(0.0)
process.analyzeHiMassTau.Muon2MetMtMaxCut = cms.double(99999.9)
process.analyzeHiMassTau.DoDiscrByElectron1MetMt = cms.bool(False)
process.analyzeHiMassTau.Electron1MetMtMinCut = cms.double(50.0)
process.analyzeHiMassTau.Electron1MetMtMaxCut = cms.double(100.0)
process.analyzeHiMassTau.DoDiscrByElectron2MetMt = cms.bool(False)
process.analyzeHiMassTau.Electron2MetMtMinCut = cms.double(0.0)
process.analyzeHiMassTau.Electron2MetMtMaxCut = cms.double(99999.9)
process.analyzeHiMassTau.DoDiscrByTau1MetMt = cms.bool(False)
process.analyzeHiMassTau.Tau1MetMtMinCut = cms.double(50.0)
process.analyzeHiMassTau.Tau1MetMtMaxCut = cms.double(100.0)
process.analyzeHiMassTau.DoDiscrByTau2MetMt = cms.bool(False)
process.analyzeHiMassTau.Tau2MetMtMinCut = cms.double(0.0)
process.analyzeHiMassTau.Tau2MetMtMaxCut = cms.double(99999.9)
process.analyzeHiMassTau.DoMuon1DiscrByIsZllCut = cms.bool(False)
process.analyzeHiMassTau.DoMuon2DiscrByIsZllCut = cms.bool(False)
process.analyzeHiMassTau.DoElectron1DiscrByIsZllCut = cms.bool(False)
process.analyzeHiMassTau.DoElectron2DiscrByIsZllCut = cms.bool(False)

    #-----do matching to gen?
process.analyzeHiMassTau.MatchLeptonToGen = cms.bool(False)                                                 # if true, match reco lepton to a gen lepton
process.analyzeHiMassTau.UseLeptonMotherId = cms.bool(False)                                                # if true, require the matched lepton to come from a certain
                                                                                        # 'mother' particle
process.analyzeHiMassTau.UseLeptonGrandMotherId = cms.bool(False)                                           # if true, require the matched lepton to come from a certain
                                                                                        # 'grandmother' particle
process.analyzeHiMassTau.LeptonMotherId = cms.int32(24)                                                     # pdgId of the 'mother' particle
process.analyzeHiMassTau.LeptonGrandMotherId = cms.int32(32)                                                # pdgId of the 'grandmother' particle
process.analyzeHiMassTau.MatchTauToGen = cms.bool(False)                                                    # if true, match reco tau to a gen had tau
process.analyzeHiMassTau.UseTauMotherId = cms.bool(False)                                                   # if true, require the matched tau to come from a certain
                                                                                        # 'mother' particle ('mother' here is NOT 15!!!!! Matching
                                                                                        # for the had tau leg already requires the vis had tau to come
                                                                                        # from a tau lepton)
process.analyzeHiMassTau.UseTauGrandMotherId = cms.bool(False)                                              # if true, require the matched tau to come from a certain
                                                                                        # 'grandmother' particle
process.analyzeHiMassTau.TauMotherId = cms.int32(25)                                                        # pdgId of the 'mother' particle
process.analyzeHiMassTau.TauGrandMotherId = cms.int32(1)                                                    # pdgId of the 'grandmother' particle
process.analyzeHiMassTau.TauToGenMatchingDeltaR = cms.double(0.25)                                          # matching dR:  dR(vis gen tau,reco tau)<X

    #-----Event Sequence inputs
process.analyzeHiMassTau.GenTauNmin = cms.int32(0)
process.analyzeHiMassTau.GenTauNmax = cms.int32(1000)
process.analyzeHiMassTau.GenTopNmin = cms.int32(0)
process.analyzeHiMassTau.GenTopNmax = cms.int32(1000)
process.analyzeHiMassTau.GenElectronNmin = cms.int32(0)
process.analyzeHiMassTau.GenElectronNmax = cms.int32(1000)
process.analyzeHiMassTau.GenMuonNmin = cms.int32(0)
process.analyzeHiMassTau.GenMuonNmax = cms.int32(1000)
process.analyzeHiMassTau.GenZNmin = cms.int32(0)
process.analyzeHiMassTau.GenZNmax = cms.int32(1000)
process.analyzeHiMassTau.GenWNmin = cms.int32(0)
process.analyzeHiMassTau.GenWNmax = cms.int32(1000)
process.analyzeHiMassTau.GenSMHiggsNmin = cms.int32(0)
process.analyzeHiMassTau.GenSMHiggsNmax = cms.int32(1000)
process.analyzeHiMassTau.RecoTriggersNmin = cms.int32(0)							# require event to pass >=X trigger paths defined above
process.analyzeHiMassTau.RecoVertexNmin = cms.int32(0)							# require event to have >=X vertices passing specified cuts
process.analyzeHiMassTau.RecoVertexNmax = cms.int32(1000)							# require event to have <=X vertices passing specified cuts
process.analyzeHiMassTau.RecoMuon1Nmin = cms.int32(1)							
process.analyzeHiMassTau.RecoMuon1Nmax = cms.int32(1000)							
process.analyzeHiMassTau.RecoMuon2Nmin = cms.int32(0)							
process.analyzeHiMassTau.RecoMuon2Nmax = cms.int32(1000)							
process.analyzeHiMassTau.RecoElectron1Nmin = cms.int32(0)							
process.analyzeHiMassTau.RecoElectron1Nmax = cms.int32(1000)							
process.analyzeHiMassTau.RecoElectron2Nmin = cms.int32(0)							
process.analyzeHiMassTau.RecoElectron2Nmax = cms.int32(1000)							
process.analyzeHiMassTau.RecoTau1Nmin = cms.int32(1)							
process.analyzeHiMassTau.RecoTau1Nmax = cms.int32(1000)							
process.analyzeHiMassTau.RecoTau2Nmin = cms.int32(0)							
process.analyzeHiMassTau.RecoTau2Nmax = cms.int32(1000)							
process.analyzeHiMassTau.RecoJetNmin = cms.int32(0)								# require event to have >=X "jets" passing specified cuts
process.analyzeHiMassTau.RecoJetNmax = cms.int32(1000)						        # require event to have <=X "jets" passing specified cuts
process.analyzeHiMassTau.RecoFirstLeadingJetNmin = cms.int32(0)
process.analyzeHiMassTau.RecoSecondLeadingJetNmin = cms.int32(0)
process.analyzeHiMassTau.RecoBJetNmin = cms.int32(0)							# require event to have >=X "jets" passing specified cuts
process.analyzeHiMassTau.RecoBJetNmax = cms.int32(1000)						        # require event to have <=X "jets" passing specified cuts
process.analyzeHiMassTau.SusyCombinationsNmin = cms.int32(0)
process.analyzeHiMassTau.DiMuonCombinationsNmin = cms.int32(0)						 
process.analyzeHiMassTau.DiMuonCombinationsNmax = cms.int32(10000)						
process.analyzeHiMassTau.DiElectronCombinationsNmin = cms.int32(0)						 
process.analyzeHiMassTau.DiElectronCombinationsNmax = cms.int32(10000)						
process.analyzeHiMassTau.DiTauCombinationsNmin = cms.int32(0)						 
process.analyzeHiMassTau.DiTauCombinationsNmax = cms.int32(10000)						
process.analyzeHiMassTau.Muon1Tau1CombinationsNmin = cms.int32(1)						 
process.analyzeHiMassTau.Muon1Tau1CombinationsNmax = cms.int32(10000)						
process.analyzeHiMassTau.Muon1Tau2CombinationsNmin = cms.int32(0)						 
process.analyzeHiMassTau.Muon1Tau2CombinationsNmax = cms.int32(10000)						
process.analyzeHiMassTau.Muon2Tau1CombinationsNmin = cms.int32(0)						 
process.analyzeHiMassTau.Muon2Tau1CombinationsNmax = cms.int32(10000)						
process.analyzeHiMassTau.Muon2Tau2CombinationsNmin = cms.int32(0)						 
process.analyzeHiMassTau.Muon2Tau2CombinationsNmax = cms.int32(10000)						
process.analyzeHiMassTau.Electron1Tau1CombinationsNmin = cms.int32(0)						 
process.analyzeHiMassTau.Electron1Tau1CombinationsNmax = cms.int32(10000)						
process.analyzeHiMassTau.Electron1Tau2CombinationsNmin = cms.int32(0)						 
process.analyzeHiMassTau.Electron1Tau2CombinationsNmax = cms.int32(10000)						
process.analyzeHiMassTau.Electron2Tau1CombinationsNmin = cms.int32(0)						 
process.analyzeHiMassTau.Electron2Tau1CombinationsNmax = cms.int32(10000)						
process.analyzeHiMassTau.Electron2Tau2CombinationsNmin = cms.int32(0)						 
process.analyzeHiMassTau.Electron2Tau2CombinationsNmax = cms.int32(10000)						
process.analyzeHiMassTau.Electron1Muon1CombinationsNmin = cms.int32(0)						 
process.analyzeHiMassTau.Electron1Muon1CombinationsNmax = cms.int32(10000)						
process.analyzeHiMassTau.Electron1Muon2CombinationsNmin = cms.int32(0)						 
process.analyzeHiMassTau.Electron1Muon2CombinationsNmax = cms.int32(10000)						
process.analyzeHiMassTau.Electron2Muon1CombinationsNmin = cms.int32(0)						 
process.analyzeHiMassTau.Electron2Muon1CombinationsNmax = cms.int32(10000)						
process.analyzeHiMassTau.Electron2Muon2CombinationsNmin = cms.int32(0)						 
process.analyzeHiMassTau.Electron2Muon2CombinationsNmax = cms.int32(10000)						

process.analyzeHiMassTau.EventSelectionSequence = cms.vstring('GenTauNmin','GenTauNmax',
                                                              'GenTopNmin','GenTopNmax',
                                                              'GenElectronNmin','GenElectronNmax',
                                                              'GenMuonNmin','GenMuonNmax',
                                                              'GenZNmin','GenZNmax',
                                                              'GenWNmin','GenWNmax',
                                                              'GenSMHiggsNmin','GenSMHiggsNmax',
                                                              'RecoTriggersNmin','RecoVertexNmin','RecoVertexNmax',
                                                              'RecoMuon1Nmin','RecoMuon1Nmax',
                                                              'RecoMuon2Nmin','RecoMuon2Nmax',
                                                              'RecoElectron1Nmin','RecoElectron1Nmax',
                                                              'RecoElectron2Nmin','RecoElectron2Nmax',
                                                              'RecoTau1Nmin','RecoTau1Nmax',
                                                              'RecoTau2Nmin','RecoTau2Nmax',
                                                              'RecoJetNmin','RecoJetNmax',
                                                              'RecoFirstLeadingJetNmin','RecoSecondLeadingJetNmin',
                                                              'RecoBJetNmin','RecoBJetNmax','SusyCombinationsNmin',
                                                              'DiMuonCombinationsNmin','DiMuonCombinationsNmax',
                                                              'DiElectronCombinationsNmin','DiElectronCombinationsNmax',
                                                              'DiTauCombinationsNmin','DiTauCombinationsNmax',
                                                              'Muon1Tau1CombinationsNmin','Muon1Tau1CombinationsNmax',
                                                              'Muon1Tau2CombinationsNmin','Muon1Tau2CombinationsNmax',
                                                              'Muon2Tau1CombinationsNmin','Muon2Tau1CombinationsNmax',
                                                              'Muon2Tau2CombinationsNmin','Muon2Tau2CombinationsNmax',
                                                              'Electron1Tau1CombinationsNmin','Electron1Tau1CombinationsNmax',
                                                              'Electron1Tau2CombinationsNmin','Electron1Tau2CombinationsNmax',
                                                              'Electron2Tau1CombinationsNmin','Electron2Tau1CombinationsNmax',
                                                              'Electron2Tau2CombinationsNmin','Electron2Tau2CombinationsNmax',
                                                              'Electron1Muon1CombinationsNmin','Electron1Muon1CombinationsNmax',
                                                              'Electron1Muon2CombinationsNmin','Electron1Muon2CombinationsNmax',
                                                              'Electron2Muon1CombinationsNmin','Electron2Muon1CombinationsNmax',
                                                              'Electron2Muon2CombinationsNmin','Electron2Muon2CombinationsNmax',
)

    #-----Inputs for systematic uncertainties
process.analyzeHiMassTau.CalculatePdfSystematicUncertanties = cms.bool(False)				# if true, pdf systematic uncertanties will be calculated
process.analyzeHiMassTau.PdfWeightTags = cms.untracked.VInputTag("cteq65PdfWeights")			# collection of weights for systematic uncertanties
process.analyzeHiMassTau.CalculateFSRSystematics = cms.bool(False)
process.analyzeHiMassTau.CalculateISRGluonSystematics = cms.bool(False)
process.analyzeHiMassTau.CalculateISRGammaSystematics = cms.bool(False)
process.analyzeHiMassTau.SmearTheMuon = cms.bool(False)
process.analyzeHiMassTau.MuonPtScaleOffset = cms.double(1.0)
process.analyzeHiMassTau.MuonPtSigmaOffset = cms.double(1.0)
process.analyzeHiMassTau.MuonEtaScaleOffset = cms.double(1.0)
process.analyzeHiMassTau.MuonEtaSigmaOffset = cms.double(1.0)
process.analyzeHiMassTau.MuonPhiScaleOffset = cms.double(1.0)
process.analyzeHiMassTau.MuonPhiSigmaOffset = cms.double(1.0)
process.analyzeHiMassTau.SmearTheElectron = cms.bool(False)
process.analyzeHiMassTau.ElectronPtScaleOffset = cms.double(1.0)
process.analyzeHiMassTau.ElectronPtSigmaOffset = cms.double(1.0)
process.analyzeHiMassTau.ElectronEtaScaleOffset = cms.double(1.0)
process.analyzeHiMassTau.ElectronEtaSigmaOffset = cms.double(1.0)
process.analyzeHiMassTau.ElectronPhiScaleOffset = cms.double(1.0)
process.analyzeHiMassTau.ElectronPhiSigmaOffset = cms.double(1.0)
process.analyzeHiMassTau.SmearTheTau = cms.bool(False)
process.analyzeHiMassTau.TauPtScaleOffset = cms.double(1.03)
process.analyzeHiMassTau.TauPtSigmaOffset = cms.double(1.0)
process.analyzeHiMassTau.TauEtaScaleOffset = cms.double(1.0)
process.analyzeHiMassTau.TauEtaSigmaOffset = cms.double(1.0)
process.analyzeHiMassTau.TauPhiScaleOffset = cms.double(1.0)
process.analyzeHiMassTau.TauPhiSigmaOffset = cms.double(1.0)
process.analyzeHiMassTau.SmearTheJet = cms.bool(False)
process.analyzeHiMassTau.UseDataBaseForJEC = cms.bool(True)
process.analyzeHiMassTau.JES_UpOrDown = cms.double(1.0)    
process.analyzeHiMassTau.JetEnergyScaleOffset = cms.double(1.0)    
process.analyzeHiMassTau.SmearThePt = cms.bool(False)
process.analyzeHiMassTau.SmearTheEta = cms.bool(False)
process.analyzeHiMassTau.SmearThePhi = cms.bool(False)
process.analyzeHiMassTau.CalculatePUSystematics = cms.bool(False)
process.analyzeHiMassTau.DataHistos = cms.string("/uscms_data/d2/jkim/ditau-5fb-1-PUweigh/CMSSW_4_2_4/src/HighMassAnalysis/Analysis/test/mht250/wjetCR/mc/puwtrue/wjet/wjetCR_data4635_mht250.root")
process.analyzeHiMassTau.MCHistos = cms.string("/uscms_data/d2/jkim/ditau-5fb-1-PUweigh/CMSSW_4_2_4/src/HighMassAnalysis/Analysis/test/mht250/wjetCR/mc/puwtrue/wjet/wjetCR_mc_wjet_mht250.root")
#    process.analyzeHiMassTau.BosonPtBinEdges = cms.untracked.vdouble(
#               0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.
#            , 10., 11., 12., 13., 14., 15., 16., 17., 18., 19.
#            , 20., 21., 22., 23., 24., 25., 26., 27., 28., 29.
#            , 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.
#            , 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.
#            , 999999.
#    )
#    process.analyzeHiMassTau.PtWeights = cms.untracked.vdouble( 
#              0.800665, 0.822121, 0.851249, 0.868285, 0.878733
#            , 0.953853, 0.928108, 0.982021, 1.00659 , 1.00648
#            , 1.03218 , 1.04924 , 1.03621 , 1.08743 , 1.01951
#            , 1.10519 , 0.984263, 1.04853 , 1.06724 , 1.10183
#            , 1.0503  , 1.13162 , 1.03837 , 1.12936 , 0.999173
#            , 1.01453 , 1.11435 , 1.10545 , 1.07199 , 1.04542
#            , 1.00828 , 1.0822  , 1.09667 , 1.16144 , 1.13906
#            , 1.27974 , 1.14936 , 1.23235 , 1.06667 , 1.06363
#            , 1.14225 , 1.22955 , 1.12674 , 1.03944 , 1.04639
#            , 1.13667 , 1.20493 , 1.09349 , 1.2107  , 1.21073
#    )
#process.analyzeHiMassTau.ApplyMuonTriggerScaleFactors = cms.bool(False)
#process.analyzeHiMassTau.ApplyElectronTriggerScaleFactors = cms.bool(False)
#process.analyzeHiMassTau.ApplyTauTriggerScaleFactors = cms.bool(False)
#    process.analyzeHiMassTau.MuonTrigPtBinEdges = cms.untracked.vdouble(0., 20., 999999.)
#    process.analyzeHiMassTau.MuonTrigPtWeights = cms.untracked.vdouble(1., 1.)
#    process.analyzeHiMassTau.MuonTrigEtaBinEdges = cms.untracked.vdouble(-999999., -2.1, -1.2, -0.8, 0.8, 1.2, 2.1, 999999.)
#    process.analyzeHiMassTau.MuonTrigEtaWeights = cms.untracked.vdouble(1., 0.9661, 0.9498, 0.9837, 0.9498, 0.9661, 1.)
#    process.analyzeHiMassTau.ElectronTrigPtBinEdges = cms.untracked.vdouble(0., 20., 999999.)
#    process.analyzeHiMassTau.ElectronTrigPtWeights = cms.untracked.vdouble(1., 1.)
#    process.analyzeHiMassTau.ElectronTrigEtaBinEdges = cms.untracked.vdouble(-999999., -2.5, -1.479, 1.479, 2.5, 999999.)
#    process.analyzeHiMassTau.ElectronTrigEtaWeights = cms.untracked.vdouble(1., 0.9713, 0.9757, 0.9713, 1.)
#    process.analyzeHiMassTau.TauTrigPtBinEdges = cms.untracked.vdouble(0., 20., 999999.)
#    process.analyzeHiMassTau.TauTrigPtWeights = cms.untracked.vdouble(1., 1.)
#    process.analyzeHiMassTau.TauTrigEtaBinEdges = cms.untracked.vdouble(-999999., -2.1, -1.2, -0.8, 0.8, 1.2, 2.1, 999999.)
#    process.analyzeHiMassTau.TauTrigEtaWeights = cms.untracked.vdouble(1., 1., 1., 1., 1., 1., 1.)

process.p = cms.Path(
  process.analyzeHiMassTau
)
